spring:
  application:
    name: ex-service-reg
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/my?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.3.101:8848
    sentinel:
      transport:
        port: 8719
        dashboard: 192.168.3.101:8080

server:
  port: 9501

mybatis:
    type-aliases-package: com.example.ex.commons.domain
    mapper-locations: classpath:mapper/*.xml

management:
  endpoints:
    web:
      exposure:
        include: "*"