spring:
  application:
    name: ex-service-consumer-item
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.3.101:8848
    sentinel:
      transport:
        port: 8719
        dashboard: 192.168.3.101:8080

server:
  port: 10205

management:
  endpoints:
    web:
      exposure:
        include: "*"